# Build settings
markdown: kramdown

# Plugins
gems: ['jekyll-paginate']

# Outputing
permalink:     /blog/:title.html
paginate: 2
paginate_path: /page:num
timezone:      null

include: ['_pages']

exclude: [vendor]

